networks:
  security-net: {}

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    hostname: keycloak.local
    environment:
      - KC_HTTP_PORT=9000
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "9000:9000"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
      - --spi-truststore-file-hostname-verification-policy=ANY # This parameter specifies the policy for verifying the hostname when establishing SSL/TLS connections using the truststore file


